package com.pla.annoyingvillagers_resurrection.combatbehaviour;

import com.pla.annoyingvillagers.combatbehaviour.CombatCommon;
import com.pla.annoyingvillagers.gameasset.AVAnimations;
import com.pla.efkick.gameasset.EFKickAnimations;
import net.corruptdog.cdm.gameasset.CorruptAnimations;
import net.shelmarow.combat_evolution.ai.CECombatBehaviors;
import net.shelmarow.combat_evolution.ai.condition.HealthCheck;
import yesman.epicfight.gameasset.Animations;
import yesman.epicfight.world.capabilities.entitypatch.MobPatch;

public class PlayerNpcResurrectionKatana {
    public static final CECombatBehaviors.Builder<MobPatch<?>> KATANA = CECombatBehaviors.builder()
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(4.0D)
                            .weight(1000.0D)
                            .maxCooldown (0)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canExecute)
                                            .withinDistance(0.0D, 5.0D)
                                            .animationBehavior(Animations.BIPED_SNEAK, 0.0F)
                                            .addExBehavior(CombatCommon::performExecute)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(3.0D)
                            .weight(1000.0D)
                            .maxCooldown (0)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .custom(CombatCommon::canEscape)
                                            .withinDistance(0.0D, 8.0D)
                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                            .addExBehavior(CombatCommon::swapToBlockToEscape)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canEscape)
                                            .withinDistance(8.0D, 48.0D)
                                            .guard(40)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(2.0D)
                            .weight(70.0D)
                            .maxCooldown (0)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .health(2.0F / 3.0F, HealthCheck.Comparator.LESS_RATIO_CONTAIN)
                                            .custom(CombatCommon::canPerformEating)
                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                            .addExBehavior(CombatCommon::performEatingAnimation)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(2.0D)
                            .weight(100.0D)
                            .maxCooldown (120)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .custom(CombatCommon::canSwapToBow)
                                            .withinDistance(7.0D, 14.0D)
                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                            .addExBehavior(CombatCommon::swapToBow)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .custom(CombatCommon::canSwapToBow)
                                            .withinDistance(7.0D, 14.0D)
                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                            .addExBehavior(CombatCommon::swapToBow)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(2.0D)
                            .weight(80.0D)
                            .maxCooldown (120)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .custom(CombatCommon::canThrowEnderPearl)
                                            .withinDistance(7.0D, 48.0D)
                                            .animationBehavior(AVAnimations.CASTING_ONE_HAND_TOP, 0.0F)
                                            .addExBehavior(CombatCommon::performEnderPearlToTarget)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(40.0D)
                            .maxCooldown(20)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 3.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO3, 0.0F)
                                                            )
                                            )
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.YAMATO_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_2, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATHING_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_C, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(EFKickAnimations.KICK_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATH_AIR_SLASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.BLADE_RUSH_FINISHER, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_RUSH, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.FATAL_DRAW_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

/* 6 */

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.YAMATO_DASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_4, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATHING_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_H, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATH_AIR_SLASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_1, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.BLADE_RUSH_FINISHER, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_2, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

/* 10 */

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.FATAL_DRAW_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.YAMATO_DASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_C, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATHING_DASH, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_4, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATH_AIR_SLASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_H, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )

                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.YAMATO_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(EFKickAnimations.KICK_3, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_AUTO1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .withinDistance(0.0D, 3.0D)
                                                            .animationBehavior(CorruptAnimations.KATANA_SHEATHING_DASH, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .withinDistance(0.0D, 4.0D)
                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO2, 0.0F)
                                                                            .addNextBehavior(
                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                            .withinDistance(0.0D, 4.0D)
                                                                                            .animationBehavior(CorruptAnimations.KATANA_AUTO3, 0.0F)
                                                                                            .addNextBehavior(
                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                                                                                            .addNextBehavior(
                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                            .animationBehavior(EFKickAnimations.KICK_2, 0.0F)
                                                                                                                            .addNextBehavior(
                                                                                                                                    CECombatBehaviors.Behavior.builder()
                                                                                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                                                                                            .withinDistance(0.0D, 5.0D)
                                                                                                                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                                                                                                                            )
                                                                                                            )
                                                                                            )
                                                                            )
                                                            )
                                            )
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(20.0D)
                            .maxCooldown (80)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_1, 0.0F)
                                            .addNextBehavior(
                                                    CECombatBehaviors.Behavior.builder()
                                                            .withinDistance(0.0D, 3.0D)
                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_2, 0.0F)
                                                            .addNextBehavior(
                                                                    CECombatBehaviors.Behavior.builder()
                                                                            .withinDistance(0.0D, 3.0D)
                                                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                                                            .animationBehavior(AVAnimations.SWORD_HEAVY_AUTO_3, 0.0F)
                                                            )
                                            )
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(10.0D)
                            .maxCooldown (80)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.YAMATO_DASH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_SHEATHING_DASH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.KATANA_SHEATH_AIR_SLASH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.BLADE_RUSH_FINISHER, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(CorruptAnimations.FATAL_DRAW_DASH, 0.0F)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(10.0D)
                            .maxCooldown(40)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .custom(CombatCommon::canThrowEnderPearl)
                                            .animationBehavior(AVAnimations.CASTING_ONE_HAND_TOP, 0.0F)
                                            .addExBehavior(CombatCommon::performEnderPearlAway)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(2.0D)
                            .maxCooldown (100)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_1, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_2, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_3, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_4, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_C, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_RUSH, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(EFKickAnimations.KICK_H, 0.0F)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(30.0D)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .custom(CombatCommon::canPerformGuarding)
                                            .guard(40)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(10.0D)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.BIPED_ROLL_BACKWARD, 0.0F)
                            )
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .withinDistance(0.0D, 3.0D)
                                            .animationBehavior(Animations.BIPED_ROLL_FORWARD, 0.0F)
                            )
            )
            .newBehaviorRoot(
                    CECombatBehaviors.BehaviorRoot.builder()
                            .priority(1.0D)
                            .weight(40.0D)
                            .maxCooldown(160)
                            .addFirstBehavior(
                                    CECombatBehaviors.Behavior.builder()
                                            .custom(CombatCommon::canPerformNormalAttackLogic)
                                            .custom(CombatCommon::canJump)
                                            .withinDistance(5.0D, 14.0D)
                                            .animationBehavior(Animations.BIPED_JUMP, 0.0F)
                                            .addExBehavior(CombatCommon::jump)
                            )
            );

}
